name: Test

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - name: Simple Test
        run: echo "✅ Build Job Running"

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - name: Simple Test
        run: echo "✅ Deploy Job Running"
